bugfix: Disallow granting health permissions to app not handling the required intents in UI as well
GrapheneOS/platform_packages_modules_Permission pull request #37
Opened 2023-10-29 06:21 UTC by quh4gko8

2023-10-29 12:28 UTC, muhomorr requested changes

2023-10-29 12:28 UTC, muhomorr commented on PermissionController/src/com/android/permissioncontroller/permission/utils/HealthPermissionUtils.java
> +        return Utils.isHealthPermissionUiEnabled() && HEALTH_PERMISSION_GROUP.equals(permGroupName);
`isHealthPermissionUiEnabled()` is much slower than `String.equals()` check. It's better to call `String.equals()` first to make this method faster in the common case.

2023-10-29 12:28 UTC, muhomorr commented on PermissionController/src/com/android/permissioncontroller/permission/utils/HealthPermissionUtils.java
> +            Log.e(HealthPermissionUtils.class.getSimpleName(), "Health connect permissions removed for " + pkgName + ". "
Outdated comment

2023-10-29 12:28 UTC, muhomorr commented on PermissionController/src/com/android/permissioncontroller/permission/utils/HealthPermissionUtils.java
> +    public static boolean isHealthPermissionAndShowing(@NonNull String permGroupName) {
Method name is confusing

2023-10-29 13:12 UTC, quh4gko8 commented on PermissionController/src/com/android/permissioncontroller/permission/utils/HealthPermissionUtils.java
> +        return Utils.isHealthPermissionUiEnabled() && HEALTH_PERMISSION_GROUP.equals(permGroupName);
Resolved in current revision

2023-10-29 13:13 UTC, quh4gko8 commented on PermissionController/src/com/android/permissioncontroller/permission/utils/HealthPermissionUtils.java
> +            Log.e(HealthPermissionUtils.class.getSimpleName(), "Health connect permissions removed for " + pkgName + ". "
Updated with more appropriate comment or log message

2023-10-29 13:28 UTC, quh4gko8 commented on PermissionController/src/com/android/permissioncontroller/permission/utils/HealthPermissionUtils.java
> +    public static boolean isHealthPermissionAndShowing(@NonNull String permGroupName) {
Changed in the latest revision, unsure if that's clear enough

2023-10-30 16:25 UTC, muhomorr commented
Commit title and PR title is incorrect, health permissions are already not grantable to such apps. This is just a UI bugfix.

2023-11-06 10:46 UTC, quh4gko8 commented
Closing in favor of https://github.com/GrapheneOS/platform_packages_modules_Permission/pull/38

2023-11-06 12:53 UTC, closed without merging